name: Deploy to EC2
on:
    push:
        branches: [main] # main 브랜치에 push될 때 실행

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm ci

            - name: Build
              env:
                  NODE_ENV: production
                  API_URL: ${{ secrets.API_URL }}
                  KAKAO_JS_KEY: a1976e486ba5c5de98358fed5bc150a5
                  ENV: development
              run: npm run build

            - name: Copy files to EC2
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.HOST_IP }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PEM_KEY }}
                  source: 'dist/*'
                  target: '/usr/share/nginx/html'
                  strip_components: 1
